// AUTO-GENERATED by scripts/build-name-sets.ts — do not edit
export const BOY = new Set(["albert","alexander","andrew","anton","arthur","benjamin","charles","daniel","david","edward","erik","ethan","felix","finn","franz","friedrich","georg","george","hans","henry","jack","jacob","james","jan","johann","johannes","john","johnny","jonas","joseph","julian","karl","leo","leon","liam","logan","louis","luca","lucas","lukas","luke","mason","matteo","matthew","maximilian","maxwell","michael","moritz","nathan","niklas","noah","oliver","oscar","paul","samuel","sebastian","theodore","thomas","till","timo","william","yannic"]);
export const GIRL = new Set(["abigail","amelia","amelie","anna","antonia","aria","aubrey","ava","carla","charlotte","chloe","clara","elisabeth","elizabeth","ella","emilia","emilie","emily","emma","franziska","frida","frieda","grace","greta","hanna","hannah","helena","helene","isabella","johanna","karla","katherine","klara","lara","laura","layla","lea","lena","leonie","lilli","lilly","lily","lina","lotte","madison","maria","marie","melina","mia","nora","olivia","paula","sarah","scarlett","sofia","sophia","sophie","teresa","theresa","victoria","zoe"]);
export const UNISEX = new Set(["alex","angel","casey","charlie","finley","franzi","jamie","jordan","kai","kim","lee","marin","micah","nic","noa","phoenix","remy","robin","ryan","sam","sascha","sasha","skyler","taylor","toni"]);
export const NICK_TO_BASE: Record<string,string> = {
  "johnny": "john",
  "jack": "john",
  "charlie": "charles",
  "chuck": "charles",
  "mike": "michael",
  "matt": "matthew",
  "ben": "benjamin",
  "joe": "joseph",
  "eddie": "edward",
  "liz": "elizabeth",
  "beth": "elizabeth",
  "liza": "elizabeth",
  "kate": "katherine",
  "katie": "katherine",
  "abby": "abigail",
  "hanna": "hannah",
  "lilli": "lilly",
  "toni": "antonia",
  "sisi": "elisabeth",
  "maddy": "madison",
  "olly": "oliver",
  "seb": "sebastian",
  "theo": "theodore",
  "will": "william",
  "tom": "thomas",
  "ed": "edward",
  "alex": "alexander"
};
