import fs from "node:fs";
import path from "node:path";

const SRC = path.resolve(__dirname, "../data/first-names-en-de.csv");
const OUT = path.resolve(__dirname, "../src/lib/text/names-generated.ts");

function norm(s: string) {
  return s.trim().toLowerCase()
    .replace(/ä/g,"ae").replace(/ö/g,"oe").replace(/ü/g,"ue").replace(/ß/g,"ss")
    .normalize("NFD").replace(/[\u0300-\u036f]/g,"")
    .replace(/[^a-z\- ]/g,"")
    .split(/[ \-]/)[0];
}

const rows = fs.readFileSync(SRC,"utf8").split(/\r?\n/).filter(Boolean);
const boys = new Set<string>();
const girls = new Set<string>();
const unisex = new Set<string>();

// Skip header row
for (const line of rows.slice(1)) {
  const [rawName, genderRaw] = line.split(",").map(s=>s?.trim());
  if (!rawName || !genderRaw) continue;
  const name = norm(rawName);
  if (!name) continue;
  const g = genderRaw.toLowerCase();
  if (g === "m") boys.add(name);
  else if (g === "f") girls.add(name);
  else if (g === "u") unisex.add(name);
}

// Common nickname mappings
const nick: Record<string,string> = {
  johnny:"john", 
  jack:"john", 
  charlie:"charles", 
  chuck:"charles",
  mike:"michael", 
  matt:"matthew", 
  ben:"benjamin", 
  joe:"joseph",
  eddie:"edward",
  liz:"elizabeth", 
  beth:"elizabeth", 
  liza:"elizabeth", 
  kate:"katherine",
  katie:"katherine", 
  abby:"abigail", 
  hanna:"hannah", 
  lilli:"lilly",
  toni:"antonia", 
  sisi:"elisabeth",
  maddy:"madison",
  olly:"oliver",
  seb:"sebastian",
  theo:"theodore",
  will:"william",
  tom:"thomas",
  ed:"edward",
  alex:"alexander"
};

const file = `// AUTO-GENERATED by scripts/build-name-sets.ts — do not edit
export const BOY = new Set(${JSON.stringify(Array.from(boys).sort())});
export const GIRL = new Set(${JSON.stringify(Array.from(girls).sort())});
export const UNISEX = new Set(${JSON.stringify(Array.from(unisex).sort())});
export const NICK_TO_BASE: Record<string,string> = ${JSON.stringify(nick, null, 2)};
`;

fs.writeFileSync(OUT, file, "utf8");
console.log(`Wrote ${OUT} with ${boys.size} boys, ${girls.size} girls, ${unisex.size} unisex names`);