#!/usr/bin/env ts-node import * as fs from 'fs';
import * as path from 'path';
import { glob } from 'glob'; interface DashStats { filesChanged: number; totalReplacements: number; emDashes: number; enDashes: number; figureDashes: number; otherDashes: number;
} // Unicode dash characters we're targeting
const EM_DASH = '\u2014'; // - (U+2014)
const EN_DASH = '\u2013'; // - (U+2013) const FIGURE_DASH = '\u2012'; // - (U+2012)
const HORIZONTAL_BAR = '\u2015'; // - (U+2015) const DASH_REGEX = /[\u2012-\u2015]/g; const stats: DashStats = { filesChanged: 0, totalReplacements: 0, emDashes: 0, enDashes: 0, figureDashes: 0, otherDashes: 0
}; function normalizeDashes(content: string): string { let modified = content; let changeCount = 0; // A) Em dash (U+2014) and Horizontal bar (U+2015): Replace with " - " const emDashPattern = /[ - - ]/g; const emDashMatches = modified.match(emDashPattern); if (emDashMatches) { stats.emDashes += emDashMatches.length; changeCount += emDashMatches.length; } modified = modified.replace(emDashPattern, ' - '); // B) En dash (U+2013) used as numeric range: Replace with "-" const numericRangePattern = /(\d)–(\d)/g; const numericMatches = modified.match(/(\d)–(\d)/g); if (numericMatches) { stats.enDashes += numericMatches.length; changeCount += numericMatches.length; } modified = modified.replace(numericRangePattern, '$1-$2'); // C) En dash between letters (compound words): Replace with "-" const compoundPattern = /([A-Za-zÄÖÜäöüß])–([A-Za-zÄÖÜäöüß])/g; const compoundMatches = modified.match(/([A-Za-zÄÖÜäöüß])–([A-Za-zÄÖÜäöüß])/g); if (compoundMatches) { stats.enDashes += compoundMatches.length; changeCount += compoundMatches.length; } modified = modified.replace(compoundPattern, '$1-$2'); // D) Spaced en dash used like a pause: Replace with " - " const spacedEnDashPattern = / - /g; const spacedMatches = modified.match(spacedEnDashPattern); if (spacedMatches) { stats.enDashes += spacedMatches.length; changeCount += spacedMatches.length; } modified = modified.replace(spacedEnDashPattern, ' - '); // E) Figure dash (U+2012) and any remaining en dashes const figureDashPattern = /-/g; const figureMatches = modified.match(figureDashPattern); if (figureMatches) { stats.figureDashes += figureMatches.length; changeCount += figureMatches.length; } // Replace figure dashes between non-spaces with "-", spaced ones with " - " modified = modified.replace(/(\S)-(\S)/g, '$1-$2'); modified = modified.replace(/ - /g, ' - '); modified = modified.replace(/-/g, '-'); // Any remaining figure dashes // F) Clean up spacing around the new hyphen pauses modified = modified.replace(/\s+-\s+/g, ' - '); // Normalize spacing around hyphens modified = modified.replace(/\s{2,}/g, ' '); // Collapse multiple spaces stats.totalReplacements += changeCount; return modified;
} function isBinaryFile(filepath: string): boolean { const binaryExtensions = [ '.png', '.jpg', '.jpeg', '.gif', '.svg', '.ico', '.woff', '.woff2', '.ttf', '.eot', '.pdf', '.zip', '.tar', '.gz', '.exe', '.dll', '.so', '.dylib' ]; const ext = path.extname(filepath).toLowerCase(); return binaryExtensions.includes(ext);
} async function processFile(filepath: string): Promise<boolean> { if (isBinaryFile(filepath)) { return false; } try { const originalContent = fs.readFileSync(filepath, 'utf8'); const normalizedContent = normalizeDashes(originalContent); if (originalContent !== normalizedContent) { fs.writeFileSync(filepath, normalizedContent, 'utf8'); console.log(`✓ Normalized dashes in: ${filepath}`); return true; } } catch (error) { console.error(`✗ Error processing ${filepath}:`, error); } return false;
} async function main() { console.log('🔍 Scanning for Unicode dashes...\n'); // Patterns for text files we want to process const patterns = [ '**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx', '**/*.md', '**/*.mdx', '**/*.json', '**/*.yml', '**/*.yaml', '**/*.css', '**/*.scss', '**/*.html', '**/*.txt' ]; // Directories to ignore const ignore = [ '**/node_modules/**', '**/.next/**', '**/.vercel/**', '**/.git/**', '**/public/media/**', '**/dist/**', '**/build/**' ]; const files = await glob(patterns, { ignore }); console.log(`Found ${files.length} text files to check\n`); // First pass: count existing dashes let totalDashesFound = 0; for (const file of files) { try { const content = fs.readFileSync(file, 'utf8'); const matches = content.match(DASH_REGEX); if (matches) { totalDashesFound += matches.length; } } catch (error) { // Skip files we can't read } } console.log(`📊 Pre-normalization audit: Found ${totalDashesFound} Unicode dashes\n`); // Second pass: normalize dashes for (const file of files) { const wasChanged = await processFile(file); if (wasChanged) { stats.filesChanged++; } } // Final summary console.log('\n📈 Dash normalization complete!'); console.log(`Files changed: ${stats.filesChanged}`); console.log(`Total replacements: ${stats.totalReplacements}`); console.log(` Em dashes ( - ): ${stats.emDashes}`); console.log(` En dashes (–): ${stats.enDashes}`); console.log(` Figure dashes (-): ${stats.figureDashes}`); console.log(` Other dashes: ${stats.otherDashes}`); // Verify no dashes remain let remainingDashes = 0; for (const file of files) { try { const content = fs.readFileSync(file, 'utf8'); const matches = content.match(DASH_REGEX); if (matches) { remainingDashes += matches.length; console.log(`⚠️ Remaining dashes in: ${file}`); } } catch (error) { // Skip files we can't read } } if (remainingDashes === 0) { console.log('✅ No Unicode dashes remaining!'); } else { console.log(`❌ ${remainingDashes} Unicode dashes still found`); process.exit(1); }
} if (require.main === module) { main().catch(console.error);
}